name: First Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First job Running"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second job Running"
